"""
scripts/build_primary_class2_vocabulary.py
Builds the complete Class 2 and Nursery/KG syllabus vocabulary for the kids AI voice agent.

Features:
1. 1-Syllable CVC 3-letter Short Vowel Families (-at, -an, -ap, -ed, -en, -et, -in, -ig, -ip, -og, -ot, -op, -un, -ug, -ut, -ub)
2. 1-Syllable Sight & Primary Words (fish, duck, frog, bird, cow, milk, star, tree, book, boat, door, cake, ball, sun...)
3. 2-Syllable Curriculum Words (rabbit, monkey, tiger, puppy, kitten, apple, mango, pencil, water, flower, rainbow...)
4. 3-Syllable Class 2 Words (elephant, butterfly, banana, tomato, potato, unicorn, umbrella, bicycle, computer...)
5. Syllable Breakups (syllables list, syllable_count, claps count, clapping speech)
6. Phonics & Spelling Breakdowns (letters list, spelling audio cues)
7. Hindi Meanings & Transliteration
"""

import json
import os

PRIMARY_VOCABULARY = [
    # =========================================================================
    # 1. CVC SHORT 'A' FAMILY (1 Syllable, 1 Clap)
    # =========================================================================
    {
        "id": "cvc_cat",
        "word": "CAT",
        "syllables": ["CAT"],
        "syllable_count": 1,
        "claps": 1,
        "category": "animals",
        "family": "-at",
        "grade_tier": "nursery",
        "hindi_word": "बिल्ली",
        "hindi_translit": "Billi",
        "phonics": "C-A-T",
        "spelling": "C-A-T",
        "spelling_letters": ["C", "A", "T"],
        "phonics_speech": "C says /k/, A says /æ/, T says /t/... C-A-T Cat! Cat maane Billi! Meow meow!",
        "syllable_speech": "Cat me 1 syllable hai! Ek taali bajao: Cat! 👏",
        "image_url": "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600",
        "sample_sentence": "The cute cat drinks sweet milk."
    },
    {
        "id": "cvc_mat",
        "word": "MAT",
        "syllables": ["MAT"],
        "syllable_count": 1,
        "claps": 1,
        "category": "home",
        "family": "-at",
        "grade_tier": "nursery",
        "hindi_word": "चटाई",
        "hindi_translit": "Chatai",
        "phonics": "M-A-T",
        "spelling": "M-A-T",
        "spelling_letters": ["M", "A", "T"],
        "phonics_speech": "M says /m/, A says /æ/, T says /t/... M-A-T Mat! Mat maane Chatai!",
        "syllable_speech": "Mat me 1 syllable hota hai! Ek taali bajao: Mat! 👏",
        "image_url": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600",
        "sample_sentence": "We sit on the clean mat."
    },
    {
        "id": "cvc_rat",
        "word": "RAT",
        "syllables": ["RAT"],
        "syllable_count": 1,
        "claps": 1,
        "category": "animals",
        "family": "-at",
        "grade_tier": "nursery",
        "hindi_word": "चूहा",
        "hindi_translit": "Chuha",
        "phonics": "R-A-T",
        "spelling": "R-A-T",
        "spelling_letters": ["R", "A", "T"],
        "phonics_speech": "R says /r/, A says /æ/, T says /t/... R-A-T Rat! Rat maane Chuha! Chhoo-chhoo!",
        "syllable_speech": "Rat me 1 syllable hai! Ek taali bajao: Rat! 👏",
        "image_url": "https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=600",
        "sample_sentence": "The little rat ran fast."
    },
    {
        "id": "cvc_bat",
        "word": "BAT",
        "syllables": ["BAT"],
        "syllable_count": 1,
        "claps": 1,
        "category": "sports",
        "family": "-at",
        "grade_tier": "nursery",
        "hindi_word": "बल्ला",
        "hindi_translit": "Balla",
        "phonics": "B-A-T",
        "spelling": "B-A-T",
        "spelling_letters": ["B", "A", "T"],
        "phonics_speech": "B says /b/, A says /æ/, T says /t/... B-A-T Bat! Bat maane Balla!",
        "syllable_speech": "Bat me 1 syllable hota hai! Ek taali bajao: Bat! 👏",
        "image_url": "https://images.unsplash.com/photo-1593341646782-e0b495cff86d?w=600",
        "sample_sentence": "I hit the ball with my cricket bat."
    },
    {
        "id": "cvc_hat",
        "word": "HAT",
        "syllables": ["HAT"],
        "syllable_count": 1,
        "claps": 1,
        "category": "clothes",
        "family": "-at",
        "grade_tier": "nursery",
        "hindi_word": "टोपी",
        "hindi_translit": "Topi",
        "phonics": "H-A-T",
        "spelling": "H-A-T",
        "spelling_letters": ["H", "A", "T"],
        "phonics_speech": "H says /h/, A says /æ/, T says /t/... H-A-T Hat! Hat maane Topi!",
        "syllable_speech": "Hat me 1 syllable hai! Ek taali bajao: Hat! 👏",
        "image_url": "https://images.unsplash.com/photo-1521369909029-2afed882baee?w=600",
        "sample_sentence": "Papa wears a round summer hat."
    },
    {
        "id": "cvc_fat",
        "word": "FAT",
        "syllables": ["FAT"],
        "syllable_count": 1,
        "claps": 1,
        "category": "adjectives",
        "family": "-at",
        "grade_tier": "lkg_ukg",
        "hindi_word": "मोटा",
        "hindi_translit": "Mota",
        "phonics": "F-A-T",
        "spelling": "F-A-T",
        "spelling_letters": ["F", "A", "T"],
        "phonics_speech": "F says /f/, A says /æ/, T says /t/... F-A-T Fat! Fat maane Mota!",
        "syllable_speech": "Fat me 1 syllable hai! Ek taali: Fat! 👏",
        "image_url": "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600",
        "sample_sentence": "The fat teddy bear is so fluffy."
    },
    {
        "id": "cvc_fan",
        "word": "FAN",
        "syllables": ["FAN"],
        "syllable_count": 1,
        "claps": 1,
        "category": "home",
        "family": "-an",
        "grade_tier": "nursery",
        "hindi_word": "पंखा",
        "hindi_translit": "Pankha",
        "phonics": "F-A-N",
        "spelling": "F-A-N",
        "spelling_letters": ["F", "A", "N"],
        "phonics_speech": "F says /f/, A says /æ/, N says /n/... F-A-N Fan! Fan maane Pankha!",
        "syllable_speech": "Fan me 1 syllable hota hai! Taali bajao: Fan! 👏",
        "image_url": "https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=600",
        "sample_sentence": "The fan gives fresh cool air."
    },
    {
        "id": "cvc_pan",
        "word": "PAN",
        "syllables": ["PAN"],
        "syllable_count": 1,
        "claps": 1,
        "category": "kitchen",
        "family": "-an",
        "grade_tier": "lkg_ukg",
        "hindi_word": "तवा",
        "hindi_translit": "Tawa",
        "phonics": "P-A-N",
        "spelling": "P-A-N",
        "spelling_letters": ["P", "A", "N"],
        "phonics_speech": "P says /p/, A says /æ/, N says /n/... P-A-N Pan! Pan maane Tawa!",
        "syllable_speech": "Pan me 1 syllable hota hai! Taali: Pan! 👏",
        "image_url": "https://images.unsplash.com/photo-1584990347449-34b8c9d46429?w=600",
        "sample_sentence": "Mummy makes delicious pancakes in the pan."
    },
    {
        "id": "cvc_van",
        "word": "VAN",
        "syllables": ["VAN"],
        "syllable_count": 1,
        "claps": 1,
        "category": "transport",
        "family": "-an",
        "grade_tier": "nursery",
        "hindi_word": "वैन",
        "hindi_translit": "Van",
        "phonics": "V-A-N",
        "spelling": "V-A-N",
        "spelling_letters": ["V", "A", "N"],
        "phonics_speech": "V says /v/, A says /æ/, N says /n/... V-A-N Van! Van maane School Van! Horn bajao: Beep beep!",
        "syllable_speech": "Van me 1 syllable hai: Van! 👏",
        "image_url": "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=600",
        "sample_sentence": "The yellow school van has arrived."
    },
    {
        "id": "cvc_man",
        "word": "MAN",
        "syllables": ["MAN"],
        "syllable_count": 1,
        "claps": 1,
        "category": "people",
        "family": "-an",
        "grade_tier": "lkg_ukg",
        "hindi_word": "आदमी",
        "hindi_translit": "Aadmi",
        "phonics": "M-A-N",
        "spelling": "M-A-N",
        "spelling_letters": ["M", "A", "N"],
        "phonics_speech": "M says /m/, A says /æ/, N says /n/... M-A-N Man! Man maane Aadmi!",
        "syllable_speech": "Man me 1 syllable hai: Man! 👏",
        "image_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600",
        "sample_sentence": "The tall man is smiling."
    },
    {
        "id": "cvc_cap",
        "word": "CAP",
        "syllables": ["CAP"],
        "syllable_count": 1,
        "claps": 1,
        "category": "clothes",
        "family": "-ap",
        "grade_tier": "nursery",
        "hindi_word": "कैप",
        "hindi_translit": "Cap",
        "phonics": "C-A-P",
        "spelling": "C-A-P",
        "spelling_letters": ["C", "A", "P"],
        "phonics_speech": "C says /k/, A says /æ/, P says /p/... C-A-P Cap! Cap maane Topi!",
        "syllable_speech": "Cap me 1 syllable hai: Cap! 👏",
        "image_url": "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600",
        "sample_sentence": "I wear my blue cap outside."
    },
    {
        "id": "cvc_map",
        "word": "MAP",
        "syllables": ["MAP"],
        "syllable_count": 1,
        "claps": 1,
        "category": "classroom",
        "family": "-ap",
        "grade_tier": "class_1",
        "hindi_word": "नक्शा",
        "hindi_translit": "Naksha",
        "phonics": "M-A-P",
        "spelling": "M-A-P",
        "spelling_letters": ["M", "A", "P"],
        "phonics_speech": "M says /m/, A says /æ/, P says /p/... M-A-P Map! Map maane Naksha!",
        "syllable_speech": "Map me 1 syllable hai: Map! 👏",
        "image_url": "https://images.unsplash.com/photo-1524661135-423995f22d0b?w=600",
        "sample_sentence": "We see oceans and countries on the map."
    },
    {
        "id": "cvc_tap",
        "word": "TAP",
        "syllables": ["TAP"],
        "syllable_count": 1,
        "claps": 1,
        "category": "home",
        "family": "-ap",
        "grade_tier": "lkg_ukg",
        "hindi_word": "नल",
        "hindi_translit": "Nal",
        "phonics": "T-A-P",
        "spelling": "T-A-P",
        "spelling_letters": ["T", "A", "P"],
        "phonics_speech": "T says /t/, A says /æ/, P says /p/... T-A-P Tap! Tap maane Nal! Tip-tip paani!",
        "syllable_speech": "Tap me 1 syllable hai: Tap! 👏",
        "image_url": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600",
        "sample_sentence": "Always turn off the water tap."
    },
    {
        "id": "cvc_bag",
        "word": "BAG",
        "syllables": ["BAG"],
        "syllable_count": 1,
        "claps": 1,
        "category": "classroom",
        "family": "-ag",
        "grade_tier": "nursery",
        "hindi_word": "बस्ता",
        "hindi_translit": "Basta",
        "phonics": "B-A-G",
        "spelling": "B-A-G",
        "spelling_letters": ["B", "A", "G"],
        "phonics_speech": "B says /b/, A says /æ/, G says /ɡ/... B-A-G Bag! Bag maane School Basta!",
        "syllable_speech": "Bag me 1 syllable hai: Bag! 👏",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600",
        "sample_sentence": "I keep my books inside my school bag."
    },

    # =========================================================================
    # 2. CVC SHORT 'E' FAMILY (1 Syllable, 1 Clap)
    # =========================================================================
    {
        "id": "cvc_bed",
        "word": "BED",
        "syllables": ["BED"],
        "syllable_count": 1,
        "claps": 1,
        "category": "home",
        "family": "-ed",
        "grade_tier": "nursery",
        "hindi_word": "बिस्तर",
        "hindi_translit": "Bistar",
        "phonics": "B-E-D",
        "spelling": "B-E-D",
        "spelling_letters": ["B", "E", "D"],
        "phonics_speech": "B says /b/, E says /e/, D says /d/... B-E-D Bed! Bed maane Bistar! Good night!",
        "syllable_speech": "Bed me 1 syllable hai: Bed! 👏",
        "image_url": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=600",
        "sample_sentence": "I sleep early on my cozy bed."
    },
    {
        "id": "cvc_red",
        "word": "RED",
        "syllables": ["RED"],
        "syllable_count": 1,
        "claps": 1,
        "category": "colors",
        "family": "-ed",
        "grade_tier": "nursery",
        "hindi_word": "लाल",
        "hindi_translit": "Laal",
        "phonics": "R-E-D",
        "spelling": "R-E-D",
        "spelling_letters": ["R", "E", "D"],
        "phonics_speech": "R says /r/, E says /e/, D says /d/... R-E-D Red! Red maane Laal rang! Jaise laal seb!",
        "syllable_speech": "Red me 1 syllable hai: Red! 👏",
        "image_url": "https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?w=600",
        "sample_sentence": "The shiny apple is bright red."
    },
    {
        "id": "cvc_hen",
        "word": "HEN",
        "syllables": ["HEN"],
        "syllable_count": 1,
        "claps": 1,
        "category": "animals",
        "family": "-en",
        "grade_tier": "nursery",
        "hindi_word": "मुर्गी",
        "hindi_translit": "Murgi",
        "phonics": "H-E-N",
        "spelling": "H-E-N",
        "spelling_letters": ["H", "E", "N"],
        "phonics_speech": "H says /h/, E says /e/, N says /n/... H-E-N Hen! Hen maane Murgi! Kukdu-koo!",
        "syllable_speech": "Hen me 1 syllable hai: Hen! 👏",
        "image_url": "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600",
        "sample_sentence": "The mother hen lays round white eggs."
    },
    {
        "id": "cvc_pen",
        "word": "PEN",
        "syllables": ["PEN"],
        "syllable_count": 1,
        "claps": 1,
        "category": "classroom",
        "family": "-en",
        "grade_tier": "nursery",
        "hindi_word": "कलम",
        "hindi_translit": "Kalam",
        "phonics": "P-E-N",
        "spelling": "P-E-N",
        "spelling_letters": ["P", "E", "N"],
        "phonics_speech": "P says /p/, E says /e/, N says /n/... P-E-N Pen! Pen maane Kalam!",
        "syllable_speech": "Pen me 1 syllable hai: Pen! 👏",
        "image_url": "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600",
        "sample_sentence": "Teacher writes gently with a blue pen."
    },
    {
        "id": "cvc_ten",
        "word": "TEN",
        "syllables": ["TEN"],
        "syllable_count": 1,
        "claps": 1,
        "category": "numbers",
        "family": "-en",
        "grade_tier": "nursery",
        "hindi_word": "दस",
        "hindi_translit": "Das",
        "phonics": "T-E-N",
        "spelling": "T-E-N",
        "spelling_letters": ["T", "E", "N"],
        "phonics_speech": "T says /t/, E says /e/, N says /n/... T-E-N Ten! Ten maane Number 10!",
        "syllable_speech": "Ten me 1 syllable hai: Ten! 👏",
        "image_url": "https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600",
        "sample_sentence": "I have ten cute little fingers."
    },
    {
        "id": "cvc_net",
        "word": "NET",
        "syllables": ["NET"],
        "syllable_count": 1,
        "claps": 1,
        "category": "sports",
        "family": "-et",
        "grade_tier": "lkg_ukg",
        "hindi_word": "जाल",
        "hindi_translit": "Jaal",
        "phonics": "N-E-T",
        "spelling": "N-E-T",
        "spelling_letters": ["N", "E", "T"],
        "phonics_speech": "N says /n/, E says /e/, T says /t/... N-E-T Net! Net maane Jaal!",
        "syllable_speech": "Net me 1 syllable hai: Net! 👏",
        "image_url": "https://images.unsplash.com/photo-1519766304817-4f37bda74a29?w=600",
        "sample_sentence": "The butterfly flew over the playground net."
    },
    {
        "id": "cvc_pet",
        "word": "PET",
        "syllables": ["PET"],
        "syllable_count": 1,
        "claps": 1,
        "category": "animals",
        "family": "-et",
        "grade_tier": "lkg_ukg",
        "hindi_word": "पालतू जानवर",
        "hindi_translit": "Paaltu Janwar",
        "phonics": "P-E-T",
        "spelling": "P-E-T",
        "spelling_letters": ["P", "E", "T"],
        "phonics_speech": "P says /p/, E says /e/, T says /t/... P-E-T Pet! Pet maane Pyara Paaltu Janwar!",
        "syllable_speech": "Pet me 1 syllable hai: Pet! 👏",
        "image_url": "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600",
        "sample_sentence": "My pet puppy loves to play fetch."
    },

    # =========================================================================
    # 3. CVC SHORT 'I' FAMILY (1 Syllable, 1 Clap)
    # =========================================================================
    {
        "id": "cvc_pin",
        "word": "PIN",
        "syllables": ["PIN"],
        "syllable_count": 1,
        "claps": 1,
        "category": "classroom",
        "family": "-in",
        "grade_tier": "lkg_ukg",
        "hindi_word": "पिन",
        "hindi_translit": "Pin",
        "phonics": "P-I-N",
        "spelling": "P-I-N",
        "spelling_letters": ["P", "I", "N"],
        "phonics_speech": "P says /p/, I says /ɪ/, N says /n/... P-I-N Pin! Pin maane Board wali Pin!",
        "syllable_speech": "Pin me 1 syllable hai: Pin! 👏",
        "image_url": "https://images.unsplash.com/photo-1584727638096-042c45049ebe?w=600",
        "sample_sentence": "Put the colorful paper with a pin on notice board."
    },
    {
        "id": "cvc_tin",
        "word": "TIN",
        "syllables": ["TIN"],
        "syllable_count": 1,
        "claps": 1,
        "category": "kitchen",
        "family": "-in",
        "grade_tier": "class_1",
        "hindi_word": "टिन का डिब्बा",
        "hindi_translit": "Tin",
        "phonics": "T-I-N",
        "spelling": "T-I-N",
        "spelling_letters": ["T", "I", "N"],
        "phonics_speech": "T says /t/, I says /ɪ/, N says /n/... T-I-N Tin! Tin maane Dabba!",
        "syllable_speech": "Tin me 1 syllable hai: Tin! 👏",
        "image_url": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600",
        "sample_sentence": "Cookies are kept inside the metal tin."
    },
    {
        "id": "cvc_pig",
        "word": "PIG",
        "syllables": ["PIG"],
        "syllable_count": 1,
        "claps": 1,
        "category": "animals",
        "family": "-ig",
        "grade_tier": "nursery",
        "hindi_word": "सुअर",
        "hindi_translit": "Suar",
        "phonics": "P-I-G",
        "spelling": "P-I-G",
        "spelling_letters": ["P", "I", "G"],
        "phonics_speech": "P says /p/, I says /ɪ/, G says /ɡ/... P-I-G Pig! Pig maane Pink Piggy! Oink oink!",
        "syllable_speech": "Pig me 1 syllable hai: Pig! 👏",
        "image_url": "https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=600",
        "sample_sentence": "The cute pink pig plays in farm."
    },
    {
        "id": "cvc_big",
        "word": "BIG",
        "syllables": ["BIG"],
        "syllable_count": 1,
        "claps": 1,
        "category": "adjectives",
        "family": "-ig",
        "grade_tier": "nursery",
        "hindi_word": "बड़ा",
        "hindi_translit": "Bada",
        "phonics": "B-I-G",
        "spelling": "B-I-G",
        "spelling_letters": ["B", "I", "G"],
        "phonics_speech": "B says /b/, I says /ɪ/, G says /ɡ/... B-I-G Big! Big maane Bada! Jaise bada haathi!",
        "syllable_speech": "Big me 1 syllable hai: Big! 👏",
        "image_url": "https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?w=600",
        "sample_sentence": "The elephant has big gray ears."
    },
    {
        "id": "cvc_lip",
        "word": "LIP",
        "syllables": ["LIP"],
        "syllable_count": 1,
        "claps": 1,
        "category": "body",
        "family": "-ip",
        "grade_tier": "nursery",
        "hindi_word": "होंठ",
        "hindi_translit": "Honth",
        "phonics": "L-I-P",
        "spelling": "L-I-P",
        "spelling_letters": ["L", "I", "P"],
        "phonics_speech": "L says /l/, I says /ɪ/, P says /p/... L-I-P Lip! Lip maane Pink Honth!",
        "syllable_speech": "Lip me 1 syllable hai: Lip! 👏",
        "image_url": "https://images.unsplash.com/photo-1588516903720-8ceb67f9ef84?w=600",
        "sample_sentence": "We smile sweetly with our lips."
    },
    {
        "id": "cvc_sit",
        "word": "SIT",
        "syllables": ["SIT"],
        "syllable_count": 1,
        "claps": 1,
        "category": "actions",
        "family": "-it",
        "grade_tier": "nursery",
        "hindi_word": "बैठना",
        "hindi_translit": "Baithna",
        "phonics": "S-I-T",
        "spelling": "S-I-T",
        "spelling_letters": ["S", "I", "T"],
        "phonics_speech": "S says /s/, I says /ɪ/, T says /t/... S-I-T Sit! Sit down please!",
        "syllable_speech": "Sit me 1 syllable hai: Sit! 👏",
        "image_url": "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600",
        "sample_sentence": "Please sit quietly on your chair."
    },

    # =========================================================================
    # 4. CVC SHORT 'O' FAMILY (1 Syllable, 1 Clap)
    # =========================================================================
    {
        "id": "cvc_dog",
        "word": "DOG",
        "syllables": ["DOG"],
        "syllable_count": 1,
        "claps": 1,
        "category": "animals",
        "family": "-og",
        "grade_tier": "nursery",
        "hindi_word": "कुत्ता",
        "hindi_translit": "Kutta",
        "phonics": "D-O-G",
        "spelling": "D-O-G",
        "spelling_letters": ["D", "O", "G"],
        "phonics_speech": "D says /d/, O says /ɒ/, G says /ɡ/... D-O-G Dog! Dog maane Wafadaar Kutta! Wuff-wuff!",
        "syllable_speech": "Dog me 1 syllable hota hai! Ek taali bajao: Dog! 👏",
        "image_url": "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600",
        "sample_sentence": "The happy dog runs in the garden."
    },
    {
        "id": "cvc_fog",
        "word": "FOG",
        "syllables": ["FOG"],
        "syllable_count": 1,
        "claps": 1,
        "category": "nature",
        "family": "-og",
        "grade_tier": "class_1",
        "hindi_word": "कोहरा",
        "hindi_translit": "Kohra",
        "phonics": "F-O-G",
        "spelling": "F-O-G",
        "spelling_letters": ["F", "O", "G"],
        "phonics_speech": "F says /f/, O says /ɒ/, G says /ɡ/... F-O-G Fog! Fog maane Sardi ka Kohra!",
        "syllable_speech": "Fog me 1 syllable hai: Fog! 👏",
        "image_url": "https://images.unsplash.com/photo-1487621167305-5d248087c724?w=600",
        "sample_sentence": "There is thick white fog in winter morning."
    },
    {
        "id": "cvc_pot",
        "word": "POT",
        "syllables": ["POT"],
        "syllable_count": 1,
        "claps": 1,
        "category": "home",
        "family": "-ot",
        "grade_tier": "nursery",
        "hindi_word": "मटका",
        "hindi_translit": "Matka",
        "phonics": "P-O-T",
        "spelling": "P-O-T",
        "spelling_letters": ["P", "O", "T"],
        "phonics_speech": "P says /p/, O says /ɒ/, T says /t/... P-O-T Pot! Pot maane Thande paani ka Matka!",
        "syllable_speech": "Pot me 1 syllable hai: Pot! 👏",
        "image_url": "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=600",
        "sample_sentence": "We keep water cool in the clay pot."
    },
    {
        "id": "cvc_hot",
        "word": "HOT",
        "syllables": ["HOT"],
        "syllable_count": 1,
        "claps": 1,
        "category": "adjectives",
        "family": "-ot",
        "grade_tier": "nursery",
        "hindi_word": "गर्म",
        "hindi_translit": "Garam",
        "phonics": "H-O-T",
        "spelling": "H-O-T",
        "spelling_letters": ["H", "O", "T"],
        "phonics_speech": "H says /h/, O says /ɒ/, T says /t/... H-O-T Hot! Hot maane Garam doodh!",
        "syllable_speech": "Hot me 1 syllable hai: Hot! 👏",
        "image_url": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600",
        "sample_sentence": "The hot milk is good for health."
    },
    {
        "id": "cvc_top",
        "word": "TOP",
        "syllables": ["TOP"],
        "syllable_count": 1,
        "claps": 1,
        "category": "toys",
        "family": "-op",
        "grade_tier": "lkg_ukg",
        "hindi_word": "लट्टू",
        "hindi_translit": "Lattu",
        "phonics": "T-O-P",
        "spelling": "T-O-P",
        "spelling_letters": ["T", "O", "P"],
        "phonics_speech": "T says /t/, O says /ɒ/, P says /p/... T-O-P Top! Top maane Ghoomne wala Lattu!",
        "syllable_speech": "Top me 1 syllable hai: Top! 👏",
        "image_url": "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600",
        "sample_sentence": "The spinning top spins round and round."
    },
    {
        "id": "cvc_fox",
        "word": "FOX",
        "syllables": ["FOX"],
        "syllable_count": 1,
        "claps": 1,
        "category": "animals",
        "family": "-ox",
        "grade_tier": "nursery",
        "hindi_word": "लोमड़ी",
        "hindi_translit": "Lomdi",
        "phonics": "F-O-X",
        "spelling": "F-O-X",
        "spelling_letters": ["F", "O", "X"],
        "phonics_speech": "F says /f/, O says /ɒ/, X says /ks/... F-O-X Fox! Fox maane Chaalaak Lomdi!",
        "syllable_speech": "Fox me 1 syllable hai: Fox! 👏",
        "image_url": "https://images.unsplash.com/photo-1516934024742-b461fba47600?w=600",
        "sample_sentence": "The clever brown fox jumped over the log."
    },
    {
        "id": "cvc_box",
        "word": "BOX",
        "syllables": ["BOX"],
        "syllable_count": 1,
        "claps": 1,
        "category": "home",
        "family": "-ox",
        "grade_tier": "nursery",
        "hindi_word": "बक्सा",
        "hindi_translit": "Baksa",
        "phonics": "B-O-X",
        "spelling": "B-O-X",
        "spelling_letters": ["B", "O", "X"],
        "phonics_speech": "B says /b/, O says /ɒ/, X says /ks/... B-O-X Box! Box maane Toys ka Baksa!",
        "syllable_speech": "Box me 1 syllable hai: Box! 👏",
        "image_url": "https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=600",
        "sample_sentence": "I keep my shiny toys in the box."
    },

    # =========================================================================
    # 5. CVC SHORT 'U' FAMILY (1 Syllable, 1 Clap)
    # =========================================================================
    {
        "id": "cvc_sun",
        "word": "SUN",
        "syllables": ["SUN"],
        "syllable_count": 1,
        "claps": 1,
        "category": "nature",
        "family": "-un",
        "grade_tier": "nursery",
        "hindi_word": "सूरज",
        "hindi_translit": "Sooraj",
        "phonics": "S-U-N",
        "spelling": "S-U-N",
        "spelling_letters": ["S", "U", "N"],
        "phonics_speech": "S says /s/, U says /ʌ/, N says /n/... S-U-N Sun! Sun maane Roshni dene wala Sooraj!",
        "syllable_speech": "Sun me 1 syllable hai: Sun! 👏",
        "image_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600",
        "sample_sentence": "The bright golden sun rises in the east."
    },
    {
        "id": "cvc_run",
        "word": "RUN",
        "syllables": ["RUN"],
        "syllable_count": 1,
        "claps": 1,
        "category": "actions",
        "family": "-un",
        "grade_tier": "nursery",
        "hindi_word": "दौड़ना",
        "hindi_translit": "Daudna",
        "phonics": "R-U-N",
        "spelling": "R-U-N",
        "spelling_letters": ["R", "U", "N"],
        "phonics_speech": "R says /r/, U says /ʌ/, N says /n/... R-U-N Run! Run maane Tez daudna!",
        "syllable_speech": "Run me 1 syllable hai: Run! 👏",
        "image_url": "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=600",
        "sample_sentence": "Children love to run and play in grass."
    },
    {
        "id": "cvc_cup",
        "word": "CUP",
        "syllables": ["CUP"],
        "syllable_count": 1,
        "claps": 1,
        "category": "kitchen",
        "family": "-up",
        "grade_tier": "nursery",
        "hindi_word": "कप",
        "hindi_translit": "Cup",
        "phonics": "C-U-P",
        "spelling": "C-U-P",
        "spelling_letters": ["C", "U", "P"],
        "phonics_speech": "C says /k/, U says /ʌ/, P says /p/... C-U-P Cup! Cup maane Milk ka Pyala!",
        "syllable_speech": "Cup me 1 syllable hai: Cup! 👏",
        "image_url": "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=600",
        "sample_sentence": "Dadi drinks warm milk from a white cup."
    },
    {
        "id": "cvc_mug",
        "word": "MUG",
        "syllables": ["MUG"],
        "syllable_count": 1,
        "claps": 1,
        "category": "home",
        "family": "-ug",
        "grade_tier": "lkg_ukg",
        "hindi_word": "मग",
        "hindi_translit": "Mug",
        "phonics": "M-U-G",
        "spelling": "M-U-G",
        "spelling_letters": ["M", "U", "G"],
        "phonics_speech": "M says /m/, U says /ʌ/, G says /ɡ/... M-U-G Mug! Bada sa Mug!",
        "syllable_speech": "Mug me 1 syllable hai: Mug! 👏",
        "image_url": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600",
        "sample_sentence": "I drink chocolate boost from my big mug."
    },
    {
        "id": "cvc_hut",
        "word": "HUT",
        "syllables": ["HUT"],
        "syllable_count": 1,
        "claps": 1,
        "category": "home",
        "family": "-ut",
        "grade_tier": "nursery",
        "hindi_word": "झोपड़ी",
        "hindi_translit": "Jhopdi",
        "phonics": "H-U-T",
        "spelling": "H-U-T",
        "spelling_letters": ["H", "U", "T"],
        "phonics_speech": "H says /h/, U says /ʌ/, T says /t/... H-U-T Hut! Hut maane Chhoti Jhopdi!",
        "syllable_speech": "Hut me 1 syllable hai: Hut! 👏",
        "image_url": "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=600",
        "sample_sentence": "There is a cozy grass hut in the village."
    },
    {
        "id": "cvc_tub",
        "word": "TUB",
        "syllables": ["TUB"],
        "syllable_count": 1,
        "claps": 1,
        "category": "home",
        "family": "-ub",
        "grade_tier": "lkg_ukg",
        "hindi_word": "टब",
        "hindi_translit": "Tub",
        "phonics": "T-U-B",
        "spelling": "T-U-B",
        "spelling_letters": ["T", "U", "B"],
        "phonics_speech": "T says /t/, U says /ʌ/, B says /b/... T-U-B Tub! Nahane ka Tub!",
        "syllable_speech": "Tub me 1 syllable hai: Tub! 👏",
        "image_url": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600",
        "sample_sentence": "The yellow duck floats in water tub."
    },

    # =========================================================================
    # 6. COMMON 1-SYLLABLE CURRICULUM SIGHT WORDS (Class 1 & 2)
    # =========================================================================
    {
        "id": "prim_fish",
        "word": "FISH",
        "syllables": ["FISH"],
        "syllable_count": 1,
        "claps": 1,
        "category": "animals",
        "family": "water_animals",
        "grade_tier": "nursery",
        "hindi_word": "मछली",
        "hindi_translit": "Machhli",
        "phonics": "F-I-S-H",
        "spelling": "F-I-S-H",
        "spelling_letters": ["F", "I", "S", "H"],
        "phonics_speech": "F-I-S-H Fish! Machhli jal ki rani hai! Jeevan uska paani hai!",
        "syllable_speech": "Fish me 1 syllable hota hai! Taali bajao: Fish! 👏",
        "image_url": "https://images.unsplash.com/photo-1524704654690-b56c05c78a00?w=600",
        "sample_sentence": "The colorful fish swims happily in blue water."
    },
    {
        "id": "prim_duck",
        "word": "DUCK",
        "syllables": ["DUCK"],
        "syllable_count": 1,
        "claps": 1,
        "category": "animals",
        "family": "birds",
        "grade_tier": "nursery",
        "hindi_word": "बतख",
        "hindi_translit": "Batakh",
        "phonics": "D-U-C-K",
        "spelling": "D-U-C-K",
        "spelling_letters": ["D", "U", "C", "K"],
        "phonics_speech": "D-U-C-K Duck! Duck maane Batakh! Quack-quack karti batakh!",
        "syllable_speech": "Duck me 1 syllable hai: Duck! 👏",
        "image_url": "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600",
        "sample_sentence": "The duck swims in the pond: quack, quack!"
    },
    {
        "id": "prim_frog",
        "word": "FROG",
        "syllables": ["FROG"],
        "syllable_count": 1,
        "claps": 1,
        "category": "animals",
        "family": "amphibians",
        "grade_tier": "lkg_ukg",
        "hindi_word": "मेंढक",
        "hindi_translit": "Mendhak",
        "phonics": "F-R-O-G",
        "spelling": "F-R-O-G",
        "spelling_letters": ["F", "R", "O", "G"],
        "phonics_speech": "F-R-O-G Frog! Frog maane Mendhak! Tarr-tarr karke koodta hai!",
        "syllable_speech": "Frog me 1 syllable hai: Frog! 👏",
        "image_url": "https://images.unsplash.com/photo-1559253664-ca249d4608c6?w=600",
        "sample_sentence": "The green frog hops from lily pad to lily pad."
    },
    {
        "id": "prim_bird",
        "word": "BIRD",
        "syllables": ["BIRD"],
        "syllable_count": 1,
        "claps": 1,
        "category": "animals",
        "family": "birds",
        "grade_tier": "nursery",
        "hindi_word": "चिड़िया",
        "hindi_translit": "Chidiya",
        "phonics": "B-I-R-D",
        "spelling": "B-I-R-D",
        "spelling_letters": ["B", "I", "R", "D"],
        "phonics_speech": "B-I-R-D Bird! Bird maane Chidiya! Chee-chee gaane wali chidiya!",
        "syllable_speech": "Bird me 1 syllable hai: Bird! 👏",
        "image_url": "https://images.unsplash.com/photo-1444464666168-49d633b86797?w=600",
        "sample_sentence": "The little bird sings sweet songs on tree branch."
    },
    {
        "id": "prim_cow",
        "word": "COW",
        "syllables": ["COW"],
        "syllable_count": 1,
        "claps": 1,
        "category": "animals",
        "family": "domestic_animals",
        "grade_tier": "nursery",
        "hindi_word": "गाय",
        "hindi_translit": "Gaay",
        "phonics": "C-O-W",
        "spelling": "C-O-W",
        "spelling_letters": ["C", "O", "W"],
        "phonics_speech": "C-O-W Cow! Cow maane Gaay mata! Moo-moo karti gaay!",
        "syllable_speech": "Cow me 1 syllable hai: Cow! 👏",
        "image_url": "https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=600",
        "sample_sentence": "The gentle cow gives fresh milk every morning."
    },
    {
        "id": "prim_milk",
        "word": "MILK",
        "syllables": ["MILK"],
        "syllable_count": 1,
        "claps": 1,
        "category": "food",
        "family": "drinks",
        "grade_tier": "nursery",
        "hindi_word": "दूध",
        "hindi_translit": "Doodh",
        "phonics": "M-I-L-K",
        "spelling": "M-I-L-K",
        "spelling_letters": ["M", "I", "L", "K"],
        "phonics_speech": "M-I-L-K Milk! Milk maane Taakatwar Doodh!",
        "syllable_speech": "Milk me 1 syllable hota hai: Milk! 👏",
        "image_url": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600",
        "sample_sentence": "Drinking a glass of milk makes our bones strong."
    },
    {
        "id": "prim_ball",
        "word": "BALL",
        "syllables": ["BALL"],
        "syllable_count": 1,
        "claps": 1,
        "category": "sports",
        "family": "play",
        "grade_tier": "nursery",
        "hindi_word": "गेंद",
        "hindi_translit": "Gend",
        "phonics": "B-A-L-L",
        "spelling": "B-A-L-L",
        "spelling_letters": ["B", "A", "L", "L"],
        "phonics_speech": "B-A-L-L Ball! Ball maane Khelne wali Bouncy Gend!",
        "syllable_speech": "Ball me 1 syllable hai: Ball! 👏",
        "image_url": "https://images.unsplash.com/photo-1519766304817-4f37bda74a29?w=600",
        "sample_sentence": "We kick and catch the round football."
    },
    {
        "id": "prim_star",
        "word": "STAR",
        "syllables": ["STAR"],
        "syllable_count": 1,
        "claps": 1,
        "category": "nature",
        "family": "sky",
        "grade_tier": "nursery",
        "hindi_word": "तारा",
        "hindi_translit": "Taara",
        "phonics": "S-T-A-R",
        "spelling": "S-T-A-R",
        "spelling_letters": ["S", "T", "A", "R"],
        "phonics_speech": "S-T-A-R Star! Twinkle twinkle little star! How I wonder what you are!",
        "syllable_speech": "Star me 1 syllable hai: Star! 👏",
        "image_url": "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=600",
        "sample_sentence": "A golden star twinkles high in the night sky."
    },
    {
        "id": "prim_tree",
        "word": "TREE",
        "syllables": ["TREE"],
        "syllable_count": 1,
        "claps": 1,
        "category": "nature",
        "family": "plants",
        "grade_tier": "nursery",
        "hindi_word": "पेड़",
        "hindi_translit": "Ped",
        "phonics": "T-R-E-E",
        "spelling": "T-R-E-E",
        "spelling_letters": ["T", "R", "E", "E"],
        "phonics_speech": "T-R-E-E Tree! Tree maane Hara bhara Ped! Chhaya aur phal deta hai!",
        "syllable_speech": "Tree me 1 syllable hota hai: Tree! 👏",
        "image_url": "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=600",
        "sample_sentence": "The big green tree gives sweet mangoes."
    },
    {
        "id": "prim_moon",
        "word": "MOON",
        "syllables": ["MOON"],
        "syllable_count": 1,
        "claps": 1,
        "category": "nature",
        "family": "sky",
        "grade_tier": "nursery",
        "hindi_word": "चाँद",
        "hindi_translit": "Chaand",
        "phonics": "M-O-O-N",
        "spelling": "M-O-O-N",
        "spelling_letters": ["M", "O", "O", "N"],
        "phonics_speech": "M-O-O-N Moon! Chanda mama door ke! Puye pakaye boor ke!",
        "syllable_speech": "Moon me 1 syllable hai: Moon! 👏",
        "image_url": "https://images.unsplash.com/photo-1532693322450-2cb5c511067d?w=600",
        "sample_sentence": "The silver moon shines in the dark sky."
    },
    {
        "id": "prim_book",
        "word": "BOOK",
        "syllables": ["BOOK"],
        "syllable_count": 1,
        "claps": 1,
        "category": "classroom",
        "family": "learning",
        "grade_tier": "nursery",
        "hindi_word": "किताब",
        "hindi_translit": "Kitaab",
        "phonics": "B-O-O-K",
        "spelling": "B-O-O-K",
        "spelling_letters": ["B", "O", "O", "K"],
        "phonics_speech": "B-O-O-K Book! Book maane Kahaniyon ki Kitaab!",
        "syllable_speech": "Book me 1 syllable hai: Book! 👏",
        "image_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600",
        "sample_sentence": "I read interesting animal stories in my picture book."
    },
    {
        "id": "prim_door",
        "word": "DOOR",
        "syllables": ["DOOR"],
        "syllable_count": 1,
        "claps": 1,
        "category": "home",
        "family": "house",
        "grade_tier": "nursery",
        "hindi_word": "दरवाजा",
        "hindi_translit": "Darwaza",
        "phonics": "D-O-O-R",
        "spelling": "D-O-O-R",
        "spelling_letters": ["D", "O", "O", "R"],
        "phonics_speech": "D-O-O-R Door! Door maane Ghar ka Darwaza!",
        "syllable_speech": "Door me 1 syllable hai: Door! 👏",
        "image_url": "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600",
        "sample_sentence": "Please knock gently on the wooden door."
    },
    {
        "id": "prim_boat",
        "word": "BOAT",
        "syllables": ["BOAT"],
        "syllable_count": 1,
        "claps": 1,
        "category": "transport",
        "family": "water_vehicles",
        "grade_tier": "lkg_ukg",
        "hindi_word": "नाव",
        "hindi_translit": "Naav",
        "phonics": "B-O-A-T",
        "spelling": "B-O-A-T",
        "spelling_letters": ["B", "O", "A", "T"],
        "phonics_speech": "B-O-A-T Boat! Row, row, row your boat gently down the stream!",
        "syllable_speech": "Boat me 1 syllable hai: Boat! 👏",
        "image_url": "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600",
        "sample_sentence": "The little paper boat floats on water."
    },
    {
        "id": "prim_cake",
        "word": "CAKE",
        "syllables": ["CAKE"],
        "syllable_count": 1,
        "claps": 1,
        "category": "food",
        "family": "sweet",
        "grade_tier": "nursery",
        "hindi_word": "केक",
        "hindi_translit": "Cake",
        "phonics": "C-A-K-E",
        "spelling": "C-A-K-E",
        "spelling_letters": ["C", "A", "K", "E"],
        "phonics_speech": "C-A-K-E Cake! Yummy birthday chocolate cake!",
        "syllable_speech": "Cake me 1 syllable hai: Cake! 👏",
        "image_url": "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600",
        "sample_sentence": "We cut a yummy chocolate cake on birthday."
    },
    {
        "id": "prim_lion",
        "word": "LION",
        "syllables": ["LI", "ON"],
        "syllable_count": 2,
        "claps": 2,
        "category": "animals",
        "family": "wild_animals",
        "grade_tier": "nursery",
        "hindi_word": "शेर",
        "hindi_translit": "Sher",
        "phonics": "L-I-O-N",
        "spelling": "L-I-O-N",
        "spelling_letters": ["L", "I", "O", "N"],
        "phonics_speech": "L-I-O-N Lion! Lion maane Jungle ka Raja Sher! Roar!",
        "syllable_speech": "Li-on me 2 syllables hote hain! Taali bajao: Li - On! 👏 👏",
        "image_url": "https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=600",
        "sample_sentence": "The mighty lion roars loud in the savannah."
    },

    # =========================================================================
    # 7. 2-SYLLABLE CURRICULUM WORDS (Class 1 & 2 - 2 Syllables, 2 Claps 👏 👏)
    # =========================================================================
    {
        "id": "syl2_rabbit",
        "word": "RABBIT",
        "syllables": ["RAB", "BIT"],
        "syllable_count": 2,
        "claps": 2,
        "category": "animals",
        "family": "two_syllable",
        "grade_tier": "lkg_ukg",
        "hindi_word": "खरगोश",
        "hindi_translit": "Khargosh",
        "phonics": "R-A-B-B-I-T",
        "spelling": "R-A-B-B-I-T",
        "spelling_letters": ["R", "A", "B", "B", "I", "T"],
        "phonics_speech": "R-A-B-B-I-T Rabbit! Safed koodne wala pyara Khargosh!",
        "syllable_speech": "Rab-bit me 2 syllables hote hain! Do baar taali bajao: Rab - Bit! 👏 👏",
        "image_url": "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=600",
        "sample_sentence": "The white rabbit loves munching crunchy carrots."
    },
    {
        "id": "syl2_monkey",
        "word": "MONKEY",
        "syllables": ["MON", "KEY"],
        "syllable_count": 2,
        "claps": 2,
        "category": "animals",
        "family": "two_syllable",
        "grade_tier": "lkg_ukg",
        "hindi_word": "बंदर",
        "hindi_translit": "Bandar",
        "phonics": "M-O-N-K-E-Y",
        "spelling": "M-O-N-K-E-Y",
        "spelling_letters": ["M", "O", "N", "K", "E", "Y"],
        "phonics_speech": "M-O-N-K-E-Y Monkey! Natkhat Bandar! Kho-kho karta hai!",
        "syllable_speech": "Mon-key me 2 syllables hote hain! Taali bajao: Mon - Key! 👏 👏",
        "image_url": "https://images.unsplash.com/photo-1540573133985-87b6da6d54a9?w=600",
        "sample_sentence": "The naughty monkey swings from tree branch."
    },
    {
        "id": "syl2_tiger",
        "word": "TIGER",
        "syllables": ["TI", "GER"],
        "syllable_count": 2,
        "claps": 2,
        "category": "animals",
        "family": "two_syllable",
        "grade_tier": "class_1",
        "hindi_word": "बाघ",
        "hindi_translit": "Baagh",
        "phonics": "T-I-G-E-R",
        "spelling": "T-I-G-E-R",
        "spelling_letters": ["T", "I", "G", "E", "R"],
        "phonics_speech": "T-I-G-E-R Tiger! Humara National Animal Baagh! Roar!",
        "syllable_speech": "Ti-ger me 2 syllables hote hain! Taali bajao: Ti - Ger! 👏 👏",
        "image_url": "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?w=600",
        "sample_sentence": "The royal Bengal tiger walks proudly."
    },
    {
        "id": "syl2_puppy",
        "word": "PUPPY",
        "syllables": ["PUP", "PY"],
        "syllable_count": 2,
        "claps": 2,
        "category": "animals",
        "family": "two_syllable",
        "grade_tier": "nursery",
        "hindi_word": "पिल्ला",
        "hindi_translit": "Pilla",
        "phonics": "P-U-P-P-Y",
        "spelling": "P-U-P-P-Y",
        "spelling_letters": ["P", "U", "P", "P", "Y"],
        "phonics_speech": "P-U-P-P-Y Puppy! Kutte ka chhota cute pilla! Yip yip!",
        "syllable_speech": "Pup-py me 2 syllables hote hain! Taali bajao: Pup - Py! 👏 👏",
        "image_url": "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600",
        "sample_sentence": "The playful puppy wags its fluffy tail."
    },
    {
        "id": "syl2_kitten",
        "word": "KITTEN",
        "syllables": ["KIT", "TEN"],
        "syllable_count": 2,
        "claps": 2,
        "category": "animals",
        "family": "two_syllable",
        "grade_tier": "nursery",
        "hindi_word": "बिल्ली का बच्चा",
        "hindi_translit": "Billi Ka Bachha",
        "phonics": "K-I-T-T-E-N",
        "spelling": "K-I-T-T-E-N",
        "spelling_letters": ["K", "I", "T", "T", "E", "N"],
        "phonics_speech": "K-I-T-T-E-N Kitten! Billi ka pyara bachha! Mew mew!",
        "syllable_speech": "Kit-ten me 2 syllables hote hain! Taali bajao: Kit - Ten! 👏 👏",
        "image_url": "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600",
        "sample_sentence": "The sweet little kitten is purring."
    },
    {
        "id": "syl2_apple",
        "word": "APPLE",
        "syllables": ["AP", "PLE"],
        "syllable_count": 2,
        "claps": 2,
        "category": "food",
        "family": "two_syllable",
        "grade_tier": "nursery",
        "hindi_word": "सेब",
        "hindi_translit": "Seb",
        "phonics": "A-P-P-L-E",
        "spelling": "A-P-P-L-E",
        "spelling_letters": ["A", "P", "P", "L", "E"],
        "phonics_speech": "A-P-P-L-E Apple! Meetha laal seb! An apple a day keeps doctor away!",
        "syllable_speech": "Ap-ple me 2 syllables hote hain! Taali bajao: Ap - Ple! 👏 👏",
        "image_url": "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=600",
        "sample_sentence": "I eat a fresh sweet apple after school."
    },
    {
        "id": "syl2_mango",
        "word": "MANGO",
        "syllables": ["MAN", "GO"],
        "syllable_count": 2,
        "claps": 2,
        "category": "food",
        "family": "two_syllable",
        "grade_tier": "nursery",
        "hindi_word": "आम",
        "hindi_translit": "Aam",
        "phonics": "M-A-N-G-O",
        "spelling": "M-A-N-G-O",
        "spelling_letters": ["M", "A", "N", "G", "O"],
        "phonics_speech": "M-A-N-G-O Mango! Phalon ka raja Aam! Yummy juicy mango!",
        "syllable_speech": "Man-go me 2 syllables hote hain! Taali bajao: Man - Go! 👏 👏",
        "image_url": "https://images.unsplash.com/photo-1553279768-865429fa0078?w=600",
        "sample_sentence": "Yellow sweet mangoes taste so good in summer."
    },
    {
        "id": "syl2_pencil",
        "word": "PENCIL",
        "syllables": ["PEN", "CIL"],
        "syllable_count": 2,
        "claps": 2,
        "category": "classroom",
        "family": "two_syllable",
        "grade_tier": "lkg_ukg",
        "hindi_word": "पेंसिल",
        "hindi_translit": "Pencil",
        "phonics": "P-E-N-C-I-L",
        "spelling": "P-E-N-C-I-L",
        "spelling_letters": ["P", "E", "N", "C", "I", "L"],
        "phonics_speech": "P-E-N-C-I-L Pencil! Likhne aur drawing banane wali Pencil!",
        "syllable_speech": "Pen-cil me 2 syllables hote hain! Taali bajao: Pen - Cil! 👏 👏",
        "image_url": "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600",
        "sample_sentence": "I sharpen my pencil to write neatly."
    },
    {
        "id": "syl2_water",
        "word": "WATER",
        "syllables": ["WA", "TER"],
        "syllable_count": 2,
        "claps": 2,
        "category": "nature",
        "family": "two_syllable",
        "grade_tier": "nursery",
        "hindi_word": "पानी",
        "hindi_translit": "Paani",
        "phonics": "W-A-T-E-R",
        "spelling": "W-A-T-E-R",
        "spelling_letters": ["W", "A", "T", "E", "R"],
        "phonics_speech": "W-A-T-E-R Water! Saaf thanda Paani! Jal hi jeevan hai!",
        "syllable_speech": "Wa-ter me 2 syllables hote hain! Taali bajao: Wa - Ter! 👏 👏",
        "image_url": "https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=600",
        "sample_sentence": "Always drink plenty of clean fresh water."
    },
    {
        "id": "syl2_flower",
        "word": "FLOWER",
        "syllables": ["FLOW", "ER"],
        "syllable_count": 2,
        "claps": 2,
        "category": "nature",
        "family": "two_syllable",
        "grade_tier": "lkg_ukg",
        "hindi_word": "फूल",
        "hindi_translit": "Phool",
        "phonics": "F-L-O-W-E-R",
        "spelling": "F-L-O-W-E-R",
        "spelling_letters": ["F", "L", "O", "W", "E", "R"],
        "phonics_speech": "F-L-O-W-E-R Flower! Sundar khushbudar Phool!",
        "syllable_speech": "Flow-er me 2 syllables hote hain! Taali: Flow - Er! 👏 👏",
        "image_url": "https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=600",
        "sample_sentence": "The red rose flower smells so sweet."
    },
    {
        "id": "syl2_rainbow",
        "word": "RAINBOW",
        "syllables": ["RAIN", "BOW"],
        "syllable_count": 2,
        "claps": 2,
        "category": "nature",
        "family": "two_syllable",
        "grade_tier": "class_1",
        "hindi_word": "इंद्रधनुष",
        "hindi_translit": "Indradhanush",
        "phonics": "R-A-I-N-B-O-W",
        "spelling": "R-A-I-N-B-O-W",
        "spelling_letters": ["R", "A", "I", "N", "B", "O", "W"],
        "phonics_speech": "R-A-I-N-B-O-W Rainbow! Saat rangon wala Indradhanush!",
        "syllable_speech": "Rain-bow me 2 syllables hote hain! Taali bajao: Rain - Bow! 👏 👏",
        "image_url": "https://images.unsplash.com/photo-1509114397022-ed747cca3f65?w=600",
        "sample_sentence": "A colorful rainbow appeared in sky after rain."
    },
    {
        "id": "syl2_teacher",
        "word": "TEACHER",
        "syllables": ["TEACH", "ER"],
        "syllable_count": 2,
        "claps": 2,
        "category": "people",
        "family": "two_syllable",
        "grade_tier": "class_1",
        "hindi_word": "अध्यापक / शिक्षिका",
        "hindi_translit": "Teacher",
        "phonics": "T-E-A-C-H-E-R",
        "spelling": "T-E-A-C-H-E-R",
        "spelling_letters": ["T", "E", "A", "C", "H", "E", "R"],
        "phonics_speech": "T-E-A-C-H-E-R Teacher! Hume nayi nayi cheezein sikhane wali Teacher!",
        "syllable_speech": "Teach-er me 2 syllables hote hain! Taali bajao: Teach - Er! 👏 👏",
        "image_url": "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=600",
        "sample_sentence": "Our kind teacher explains lessons gently."
    },
    {
        "id": "syl2_window",
        "word": "WINDOW",
        "syllables": ["WIN", "DOW"],
        "syllable_count": 2,
        "claps": 2,
        "category": "home",
        "family": "two_syllable",
        "grade_tier": "class_1",
        "hindi_word": "खिड़की",
        "hindi_translit": "Khidki",
        "phonics": "W-I-N-D-O-W",
        "spelling": "W-I-N-D-O-W",
        "spelling_letters": ["W", "I", "N", "D", "O", "W"],
        "phonics_speech": "W-I-N-D-O-W Window! Ghar ki Khidki jahan se taazi hawa aati hai!",
        "syllable_speech": "Win-dow me 2 syllables hote hain! Taali: Win - Dow! 👏 👏",
        "image_url": "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600",
        "sample_sentence": "Look outside the window at the green garden."
    },

    # =========================================================================
    # 8. 3-SYLLABLE CLASS 2 CURRICULUM WORDS (3 Syllables, 3 Claps 👏 👏 👏)
    # =========================================================================
    {
        "id": "syl3_elephant",
        "word": "ELEPHANT",
        "syllables": ["EL", "E", "PHANT"],
        "syllable_count": 3,
        "claps": 3,
        "category": "animals",
        "family": "three_syllable",
        "grade_tier": "class_2",
        "hindi_word": "हाथी",
        "hindi_translit": "Haathi",
        "phonics": "E-L-E-P-H-A-N-T",
        "spelling": "E-L-E-P-H-A-N-T",
        "spelling_letters": ["E", "L", "E", "P", "H", "A", "N", "T"],
        "phonics_speech": "E-L-E-P-H-A-N-T Elephant! Lambi soond wala Haathi raja! Paawoo!",
        "syllable_speech": "El-e-phant me 3 syllables hote hain! Teen taali bajayein: El - e - phant! 👏 👏 👏",
        "image_url": "https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?w=600",
        "sample_sentence": "The big elephant showers cool water with its long trunk."
    },
    {
        "id": "syl3_butterfly",
        "word": "BUTTERFLY",
        "syllables": ["BUT", "TER", "FLY"],
        "syllable_count": 3,
        "claps": 3,
        "category": "animals",
        "family": "three_syllable",
        "grade_tier": "class_2",
        "hindi_word": "तितली",
        "hindi_translit": "Titli",
        "phonics": "B-U-T-T-E-R-F-L-Y",
        "spelling": "B-U-T-T-E-R-F-L-Y",
        "spelling_letters": ["B", "U", "T", "T", "E", "R", "F", "L", "Y"],
        "phonics_speech": "B-U-T-T-E-R-F-L-Y Butterfly! Rangeen pankhon wali Titli rani!",
        "syllable_speech": "But-ter-fly me 3 syllables hote hain! Teen taali bajao: But - ter - fly! 👏 👏 👏",
        "image_url": "https://images.unsplash.com/photo-1559827291-72ee739d0d9a?w=600",
        "sample_sentence": "The colorful butterfly dances on garden flowers."
    },
    {
        "id": "syl3_banana",
        "word": "BANANA",
        "syllables": ["BA", "NA", "NA"],
        "syllable_count": 3,
        "claps": 3,
        "category": "food",
        "family": "three_syllable",
        "grade_tier": "class_2",
        "hindi_word": "केला",
        "hindi_translit": "Kela",
        "phonics": "B-A-N-A-N-A",
        "spelling": "B-A-N-A-N-A",
        "spelling_letters": ["B", "A", "N", "A", "N", "A"],
        "phonics_speech": "B-A-N-A-N-A Banana! Meetha peela Kela! Bandar ka favourite!",
        "syllable_speech": "Ba-na-na me 3 syllables hote hain! Teen taali bajao: Ba - na - na! 👏 👏 👏",
        "image_url": "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=600",
        "sample_sentence": "A sweet yellow banana gives lots of energy."
    },
    {
        "id": "syl3_tomato",
        "word": "TOMATO",
        "syllables": ["TO", "MA", "TO"],
        "syllable_count": 3,
        "claps": 3,
        "category": "food",
        "family": "three_syllable",
        "grade_tier": "class_2",
        "hindi_word": "टमाटर",
        "hindi_translit": "Tamatar",
        "phonics": "T-O-M-A-T-O",
        "spelling": "T-O-M-A-T-O",
        "spelling_letters": ["T", "O", "M", "A", "T", "O"],
        "phonics_speech": "T-O-M-A-T-O Tomato! Laal tamatar bada mazedaar!",
        "syllable_speech": "To-ma-to me 3 syllables hote hain! Teen taali: To - ma - to! 👏 👏 👏",
        "image_url": "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600",
        "sample_sentence": "Mummy adds juicy red tomato in soup."
    },
    {
        "id": "syl3_potato",
        "word": "POTATO",
        "syllables": ["PO", "TA", "TO"],
        "syllable_count": 3,
        "claps": 3,
        "category": "food",
        "family": "three_syllable",
        "grade_tier": "class_2",
        "hindi_word": "आलू",
        "hindi_translit": "Aaloo",
        "phonics": "P-O-T-A-T-O",
        "spelling": "P-O-T-A-T-O",
        "spelling_letters": ["P", "O", "T", "A", "T", "O"],
        "phonics_speech": "P-O-T-A-T-O Potato! Aalu kachalu beta kahan gaye the?",
        "syllable_speech": "Po-ta-to me 3 syllables hote hain! Teen taali: Po - ta - to! 👏 👏 👏",
        "image_url": "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600",
        "sample_sentence": "Crispy golden potato chips are tasty."
    },
    {
        "id": "syl3_umbrella",
        "word": "UMBRELLA",
        "syllables": ["UM", "BREL", "LA"],
        "syllable_count": 3,
        "claps": 3,
        "category": "clothes",
        "family": "three_syllable",
        "grade_tier": "class_2",
        "hindi_word": "छाता",
        "hindi_translit": "Chhata",
        "phonics": "U-M-B-R-E-L-L-A",
        "spelling": "U-M-B-R-E-L-L-A",
        "spelling_letters": ["U", "M", "B", "R", "E", "L", "L", "A"],
        "phonics_speech": "U-M-B-R-E-L-L-A Umbrella! Baarish se bachane wali colorful Chhatri!",
        "syllable_speech": "Um-brel-la me 3 syllables hote hain! Teen taali: Um - brel - la! 👏 👏 👏",
        "image_url": "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=600",
        "sample_sentence": "Open your bright umbrella when raindrops fall."
    },
    {
        "id": "syl3_bicycle",
        "word": "BICYCLE",
        "syllables": ["BI", "CY", "CLE"],
        "syllable_count": 3,
        "claps": 3,
        "category": "transport",
        "family": "three_syllable",
        "grade_tier": "class_2",
        "hindi_word": "साइकिल",
        "hindi_translit": "Cycle",
        "phonics": "B-I-C-Y-C-L-E",
        "spelling": "B-I-C-Y-C-L-E",
        "spelling_letters": ["B", "I", "C", "Y", "C", "L", "E"],
        "phonics_speech": "B-I-C-Y-C-L-E Bicycle! Do pahiye wali sundar Cycle! Tring tring!",
        "syllable_speech": "Bi-cy-cle me 3 syllables hote hain! Teen taali: Bi - cy - cle! 👏 👏 👏",
        "image_url": "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=600",
        "sample_sentence": "I ride my small red bicycle in park."
    },
    {
        "id": "syl3_dinosaur",
        "word": "DINOSAUR",
        "syllables": ["DI", "NO", "SAUR"],
        "syllable_count": 3,
        "claps": 3,
        "category": "animals",
        "family": "three_syllable",
        "grade_tier": "class_2",
        "hindi_word": "डायनासोर",
        "hindi_translit": "Dinosaur",
        "phonics": "D-I-N-O-S-A-U-R",
        "spelling": "D-I-N-O-S-A-U-R",
        "spelling_letters": ["D", "I", "N", "O", "S", "A", "U", "R"],
        "phonics_speech": "D-I-N-O-S-A-U-R Dinosaur! Bada sa prehistoric Dinosaur! Rawr!",
        "syllable_speech": "Di-no-saur me 3 syllables hote hain! Teen taali: Di - no - saur! 👏 👏 👏",
        "image_url": "https://images.unsplash.com/photo-1525877442103-5ddb2089e2bb?w=600",
        "sample_sentence": "The giant dinosaur had large footprint."
    },
    {
        "id": "syl3_computer",
        "word": "COMPUTER",
        "syllables": ["COM", "PU", "TER"],
        "syllable_count": 3,
        "claps": 3,
        "category": "classroom",
        "family": "three_syllable",
        "grade_tier": "class_2",
        "hindi_word": "कंप्यूटर",
        "hindi_translit": "Computer",
        "phonics": "C-O-M-P-U-T-E-R",
        "spelling": "C-O-M-P-U-T-E-R",
        "spelling_letters": ["C", "O", "M", "P", "U", "T", "E", "R"],
        "phonics_speech": "C-O-M-P-U-T-E-R Computer! Smart Computer jo hume sikhata hai!",
        "syllable_speech": "Com-pu-ter me 3 syllables hote hain! Teen taali: Com - pu - ter! 👏 👏 👏",
        "image_url": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600",
        "sample_sentence": "We learn typing games on the computer."
    }
]

def main():
    target_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "kids")
    os.makedirs(target_dir, exist_ok=True)

    # 1. Write primary_class2_vocabulary.json
    out_vocab = os.path.join(target_dir, "primary_class2_vocabulary.json")
    with open(out_vocab, "w", encoding="utf-8") as f:
        json.dump(PRIMARY_VOCABULARY, f, ensure_ascii=False, indent=2)

    # 2. Update english_reading_words.json with the full enriched vocabulary
    out_reading = os.path.join(target_dir, "english_reading_words.json")
    reading_words = []
    for item in PRIMARY_VOCABULARY:
        reading_words.append({
            "id": f"ew_{item['word'].lower()}",
            "word": item["word"],
            "hindi_word": f"{item['word']} ({item['hindi_word']})",
            "vowel_group": item["family"],
            "syllables": item.get("syllables", [item["word"]]),
            "syllable_count": item.get("syllable_count", 1),
            "claps": item.get("claps", 1),
            "letters": list(item["word"]),
            "letter_sounds": list(item["phonics"].replace("-", "")),
            "curriculum_tier": item["grade_tier"],
            "phonics_speech": item["phonics_speech"],
            "syllable_speech": item.get("syllable_speech", f"{item['word']} has {item.get('syllable_count', 1)} syllable!"),
            "image_url": item["image_url"],
            "sentence": item["sample_sentence"]
        })
    with open(out_reading, "w", encoding="utf-8") as f:
        json.dump(reading_words, f, ensure_ascii=False, indent=2)

    print(f"==================================================")
    print(f"[OK] Generated {len(PRIMARY_VOCABULARY)} Class 2 Syllabus words with Syllables & Phonics!")
    print(f"- Saved to: {out_vocab}")
    print(f"- Updated: {out_reading}")
    print(f"==================================================")

if __name__ == "__main__":
    main()
